context:
  version: "29.7.2"

package:
  name: docker-cli
  version: ${{ version }}

source:
  url: https://github.com/docker/cli/archive/v${{ version }}.tar.gz
  sha256: 225b7ab2a15f5230b482df8461069cd4bce38891266fb9898d4188d0a3cbf54a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ stdlib('c') }}
    - go-licenses
    - if: unix
      then:
        - go-md2man
        - sed
      else: m2-sed
tests:
  - script:
      - docker --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Pack, ship and run any application as a lightweight container
  homepage: https://github.com/docker/cli
  repository: https://github.com/docker/cli

extra:
  recipe-maintainers:
    - danielnachun
